interface Records {
    id: number;
    name: string;
    email: string,
    role: Array<string>;
}

const records: Records[] = [
    {
        id: 1,
        name: "Burt",
        email: "Burt@gmail.com",
        role: ["Receptionist"],
    },
    {
        id: 2,
        name: "Bruno",
        email: "Bruno@gmail.com",
        role: ["Administrator"],
    },
    {
        id: 3,
        name: "Alvarado",
        email: "Alvarado@gmail.com",
        role: [""],
    },
    {
        id: 4,
        name: "Lilia",
        email: "Lilia@gmail.com",
        role: ["Administrator", "Pathologist"],
    },
    {
        id: 5,
        name: "Amanda",
        email: "Amanda@gmail.com",
        role: ["Pathologist"],
    },
    {
        id: 6,
        name: "Alexandra",
        email: "Alexandra@gmail.com",
        role: ["super_admin"],
    },
    {
        id: 7,
        name: "Diana",
        email: "Diana@gmail.com",
        role: ["Administrator"],
    },
    {
        id: 8,
        name: "Goodman",
        email: "Goodman@gmail.com",
        role: ["Pathologist"],
    },
    {
        id: 9,
        name: "Edith",
        email: "Edith@gmail.com",
        role: ["Receptionist"],
    },
    {
        id: 10,
        name: "Juana",
        email: "Juana@gmail.com",
        role: ["Receptionist"],
    },
    {
        id: 11,
        name: "Fitzgerald",
        email: "Fitzgerald@gmail.com",
        role: ["Receptionist"],
    },
    {
        id: 12,
        name: "Madden",
        email: "Corpulse@gmail.com",
        role: ["Receptionist"],
    },
    {
        id: 13,
        name: "Jewell",
        email: "Frenex@gmail.com",
        role: ["Receptionist"],
    },
    {
        id: 14,
        name: "Kerr",
        email: "Artiq@gmail.com",
        role: ["Pathologist"],
    },
    {
        id: 15,
        name: "Washington",
        email: "Organica@gmail.com",
        role: ["Pathologist"],
    },
    {
        id: 16,
        name: "Audrey",
        email: "Softmicro@gmail.com",
        role: ["Pathologist"],
    },
    {
        id: 17,
        name: "Allison",
        email: "Playce@gmail.com",
        role: ["Pathologist"],
    },
    {
        id: 18,
        name: "Holder",
        email: "Paragonia@gmail.com",
        role: ["Pathologist"],
    },
    {
        id: 19,
        name: "Atkinson",
        email: "Scentric@gmail.com",
        role: ["Pathologist"],
    },
    {
        id: 20,
        name: "Delaney",
        email: "Telpod@gmail.com",
        role: ["Pathologist"],
    },
    {
        id: 21,
        name: "Myrna",
        email: "Zanity@gmail.com",
        role: ["Pathologist"],
    },
    {
        id: 22,
        name: "Erna",
        email: "Techade@gmail.com",
       role: ["Pathologist"],
    },
    {
        id: 23,
        name: "Fannie",
        email: "Cubix@gmail.com",
       role: ["Pathologist"],
    },
    {
        id: 24,
        name: "Melody",
        email: "Talae@gmail.com",
       role: ["Pathologist"],
    },
    {
        id: 25,
        name: "Letitia",
        email: "Enjola@gmail.com",
       role: ["Pathologist"],
    },
    {
        id: 26,
        name: "Nina",
        email: "Eventex@gmail.com",
       role: ["Pathologist"],
    },
    {
        id: 27,
        name: "Byrd",
        email: "Obones@gmail.com",
       role: ["Pathologist"],
    },
    {
        id: 28,
        name: "Chen",
        email: "Dadabase@gmail.com",
       role: ["Pathologist"],
    },
    {
        id: 29,
        name: "Alexandria",
        email: "Turnabout@gmail.com",
       role: ["Pathologist"],
    },
    {
        id: 30,
        name: "Page",
        email: "Metroz@gmail.com",
       role: ["Pathologist"],
    },
    {
        id: 31,
        name: "Clare",
        email: "Zilch@gmail.com",
       role: ["Pathologist"],
    },
    {
        id: 32,
        name: "Lindsey",
        email: "Roughies@gmail.com",
         role: ["Administrator", "Pathologist"],
    },
    {
        id: 33,
        name: "Oconnor",
        email: "Kinetica@gmail.com",
         role: ["Administrator", "Pathologist"],
    },
    {
        id: 34,
        name: "Maldonado",
        email: "Zentime@gmail.com",
         role: ["Administrator", "Pathologist"],
    },
    {
        id: 35,
        name: "Day",
        email: "Eargo@gmail.com",
         role: ["Administrator", "Pathologist"],
    },
    {
        id: 36,
        name: "Collier",
        email: "Phuel@gmail.com",
         role: ["Administrator", "Pathologist"],
    },
    {
        id: 37,
        name: "Jeannette",
        email: "Entogrok@gmail.com",
         role: ["Administrator", "Pathologist"],
    },
    {
        id: 38,
        name: "Wallace",
        email: "Nurali@gmail.com",
         role: ["Administrator", "Pathologist"],
    },
    {
        id: 39,
        name: "Mcfadden",
        email: "Cincyr@gmail.com",
         role: ["Administrator", "Pathologist"],
    },
    {
        id: 40,
        name: "Chrystal",
        email: "Futurize@gmail.com",
         role: ["Administrator", "Pathologist"],
    },
    {
        id: 41,
        name: "Leila",
        email: "Zensure@gmail.com",
         role: ["Administrator", "Pathologist"],
    },
    {
        id: 42,
        name: "Madelyn",
        email: "Egypto@gmail.com",
         role: ["Administrator", "Pathologist"],
    },
    {
        id: 43,
        name: "Peck",
        email: "Tellifly@gmail.com",
         role: ["Administrator", "Pathologist"],
    },
    {
        id: 44,
        name: "Garrett",
        email: "Aquasure@gmail.com",
         role: ["Administrator", "Pathologist"],
    },
    {
        id: 45,
        name: "Kramer",
        email: "Terrago@gmail.com",
         role: ["Administrator", "Pathologist"],
    },
    {
        id: 46,
        name: "Lane",
        email: "Anivet@gmail.com",
         role: ["Administrator", "Pathologist"],
    },
    {
        id: 47,
        name: "Merritt",
        email: "Inear@gmail.com",
         role: ["Administrator", "Pathologist"],
    },
    {
        id: 48,
        name: "Margarita",
        email: "Unq@gmail.com",
         role: ["Administrator", "Pathologist"],
    },
    {
        id: 49,
        name: "Leigh",
        email: "Marqet@gmail.com",
       role: ["super_admin"],
    },
    {
        id: 50,
        name: "Coleman",
        email: "Insuresys@gmail.com",
       role: ["super_admin"],
    },
    {
        id: 51,
        name: "Alexander",
        email: "Portico@gmail.com",
       role: ["super_admin"],
    },
    {
        id: 52,
        name: "Tanisha",
        email: "Earthwax@gmail.com",
       role: ["super_admin"],
    },
    {
        id: 53,
        name: "Crane",
        email: "Pushcart@gmail.com",
       role: ["super_admin"],
    },
    {
        id: 54,
        name: "Carmella",
        email: "Acusage@gmail.com",
       role: ["super_admin"],
    },
    {
        id: 55,
        name: "Rosalind",
        email: "Isologica@gmail.com",
       role: ["super_admin"],
    },
    {
        id: 56,
        name: "Duran",
        email: "Gazak@gmail.com",
        role: ["Pathologist"],
    },
    {
        id: 57,
        name: "Bernard",
        email: "Zoinage@gmail.com",
        role: ["Pathologist"],
    },
    {
        id: 58,
        name: "Tate",
        email: "Endipine@gmail.com",
        role: ["Pathologist"],
    },
    {
        id: 59,
        name: "Pearlie",
        email: "Progenex@gmail.com",
        role: ["Pathologist"],
    },
    {
        id: 60,
        name: "Manning",
        email: "Handshake@gmail.com",
        role: ["Pathologist"],
    },
]
 export { records };
